# https://cloud.google.com/solutions/continuous-delivery-with-travis-ci
language: android
group: travis_lts
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/gcloud-sdk/"
env:
  - PATH=${HOME}/gcloud-sdk/bin:$PATH CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - yes | sdkmanager "platforms;android-27"
  - export TRAVIS_GIT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export GIT_SHA=$(git rev-parse HEAD)
  - export GIT_MERGE_BASE=$(git merge-base master)
  - echo GIT_SHA $GIT_SHA
  - echo GIT_MERGE_BASE $GIT_MERGE_BASE
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
jdk:
  - oraclejdk8
branches:
  except:
    - gh-pages
notifications:
  email: false
jobs:
  include:
    - stage: "test"
      name: "check"
      script: ./gradlew check
    - name: "firebase"
      script:
        - ./gradlew :LottieSample:assembleDebug
        - ./gcloud_run.sh
sudo: false
